[tool.poetry]
name = "cisi-project"
version = "0.1.0"
description = ""
authors = ["Sergio Picascia <sergiopicascia@libero.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
